version: '3'

services:
    node:
        image: node
        container_name: ${PREFIX_CONTAINERS}node
        restart: "no"
        ports:
        - 8082:8080
        command: npx nodemon index.js
        working_dir: /nodeserv
        volumes:
            - ./node:/nodeserv
        depends_on:
            - database

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PREFIX_CONTAINERS}phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment: 
            PMA_HOST: ${PREFIX_CONTAINERS}mysql
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: "root"
        depends_on:
            - database

    database:
        image: mysql:5.7.22
        container_name: ${PREFIX_CONTAINERS}mysql
        restart: always
        ports:
            - 8081:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: mallowz
            MYSQL_USER: mallowz
            MYSQL_PASSWORD: mallowz
            TZ: Europe/Amsterdam
